Removing the deploy folder from the lira repository
HumanCellAtlas/lira pull request #135
Opened 2019-02-25 20:04 UTC by rhiananthony

### Purpose
The purpose of this PR is to remove the deployment folder from the Lira repository since deployments will use the secondary-analysis-deploy repo going forward

- No issue is linked to this PR.
---
### Changes
_Please list out what major changes were made in this PR to address the issue:_

- No changes.
---
### Review Instructions
_Please provide instructions about how should a reviewer test/verify the changes in this PR:_

- No instructions.

---
### PR Checklist
_Please ensure the following when opening a PR:_

- [ ] This PR added or updated tests.
- [ ] This PR updated docstrings or documentation.
- [ ] This PR applied Python style guidelines, specifically followed [Google style docstrings](https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html#example-google) for this repo.
- [ ] This PR considered generalizability beyond our own use case.

---
### Follow-up Discussions
_Please append follow-up discussions and issues during the review process below:_

- No follow-up discussions.

2019-02-25 21:44 UTC, rexwangcc commented on deploy/README.md
> -### Create Service Accounts
It's OK to remove this file, but I think we need to make sure these paragraphs eventually are covered by the documentation of the Lira on, say ReadtheDocs. @rhiananthony @samanehsan

2019-02-25 21:45 UTC, rexwangcc approved these changes

2019-02-25 21:56 UTC, rhiananthony commented on deploy/README.md
> -### Create Service Accounts
Ok, then I shouldn't merge this until that work is done. I'll do that next

2019-02-28 19:07 UTC, samanehsan commented on deploy/README.md
> -### Create Service Accounts
How about adding a deployment section to the Lira readme that includes a link to the `secondary-analysis-deploy` repo?

2019-03-20 20:41 UTC, samanehsan commented
LGTM @rhiananthony! As for documentation, I suggest adding a deployment section to the Lira README with a link to the secondary-analysis-deploy repo :octocat: 🌤

2019-04-01 19:39 UTC, rexwangcc requested changes
We might also want to remove the `.gitlab-ci.yml` file.

2019-05-14 19:37 UTC, samanehsan commented
LGTM @rhiananthony! I think it's confusing to leave this in since we're now using the secondary-analysis-deploy repo :octocat:

2019-07-08 15:45 UTC, merged