Add linting integration for Lira.
HumanCellAtlas/lira pull request #154
Opened 2019-03-29 17:23 UTC by rexwangcc

https://broadinstitute.atlassian.net/jira/software/projects/GH/boards/530

## Changes:
- [x] Add [Black](https://black.readthedocs.io/en/stable/index.html) as the code formatter for Falcon.
- [x] Add Flake-8 and its configuration to the repo.
- [x] Update the Travis CI config so we have a linting test before all of the other tests.
- [x] Add `pre-commit` and update the requirements as well as the readme.
- [x] Add some status badges.
 

## Review+QA Instructions:

- Please check if there are any deal-breakers that Black provides here, for instance:
    - Do you think it's OK to always add `()` everywhere? Black adds them almost everywhere.
    - Do you think it's OK to have extra lines?
    - Do you think it's OK to always dedent the closing brackets and add a trailing comma? Black does that to produce smaller diffs in code reviews.
    - etc.
- Please check the new multi-stage test on Travis
- Please follow the updated readme, make sure the `pre-commit` is installed on your local environment and if feasible, try to make a commit (e.g. add an empty line to the readme, but don't push it), see if the hook works.

2019-03-29 19:27 UTC, samanehsan commented
Since this tool applies python styles, what do you think about removing `This PR applied Python style guidelines, specifically followed Google style docstrings for this repo.` from the [pull request template](https://github.com/HumanCellAtlas/lira/blob/master/pull_request_template.md)?

2019-03-29 19:31 UTC, samanehsan commented on README.md
> +2. Make sure the `.pre-commit-config.yaml` still looks OK to you.
Does installing `pre-commit` modify the `.pre-commit-config.yaml`? I think it's clearer to say "Make sure the `.pre-commit-config.yaml` uses the same configuration as Lira <link to `.pre-commit-config.yaml`>"

2019-03-29 19:33 UTC, samanehsan commented on .flake8
> +# F401  module imported but unused
Style nit: Can you make the spacing consistent between the style code and descriptions?

2019-04-01 19:30 UTC, samanehsan approved these changes

2019-04-03 14:36 UTC, samanehsan commented on .flake8
> +# F401  module imported but unused
I would prefer to disable this rule at the line level since there may be some cases where we want this to occur, but not all cases.

2019-04-03 14:41 UTC, samanehsan commented on README.md
> +2. Run `pre-commit install` to install the git hook.
Please include a note about what command to run to do the linting/formatting!

2019-04-03 14:43 UTC, samanehsan commented on .flake8
> +# F401  module imported but unused
Can you please fix the spacing here? Lines 4 & 6 only have one space before the description but the others have two spaces.

2019-04-03 14:44 UTC, samanehsan requested changes
Left a few comments!

2019-04-03 15:07 UTC, rexwangcc commented on README.md
> +2. Run `pre-commit install` to install the git hook.
Once you install the hooks, the linting/formatting will run automatically! Adding it to the readme!

2019-04-03 15:07 UTC, rexwangcc commented on .flake8
> +# F401  module imported but unused
Sure, that makes sense, let me add noqa at line levels!

2019-04-03 15:12 UTC, samanehsan commented on README.md
> +2. Run `pre-commit install` to install the git hook.
Oh! Of course that is what a pre-commit hook does :octocat: 🤦‍♀️

2019-04-03 15:27 UTC, rexwangcc commented on .flake8
> +# F401  module imported but unused
Oh, I didn't notice that, might have used tabs by accident. Good catch! Will do

2019-04-03 15:27 UTC, rexwangcc commented on .flake8
> +# F401  module imported but unused
done

2019-04-03 15:56 UTC, tbl3rd approved these changes
I have no useful opinion on Python formatting.

2019-04-03 15:56 UTC, tbl3rd commented on .pre-commit-config.yaml
> +      # Using args here is not recommended by Black:
Some trailing whitespace in this file, starting on this line.

2019-04-03 15:56 UTC, tbl3rd commented on .travis.yml
> +      script:
Trailing space here too.

2019-04-03 19:36 UTC, samanehsan approved these changes

2019-04-08 14:55 UTC, rexwangcc commented
retest this please

2019-04-08 20:17 UTC, merged