[WIP] Add smartseq2 query for v5 metadata
HumanCellAtlas/lira pull request #60
Opened 2018-03-07 08:58 UTC by samanehsan

Add query for smartseq2 bundles that follows the v5 metadata schema: https://github.com/HumanCellAtlas/metadata-schema/tree/develop

2018-03-07 09:32 UTC, hannes-ucsc commented
This looks like it's not the final version we came up with yesterday?

2018-03-07 11:49 UTC, hannes-ucsc approved these changes

2018-03-07 11:53 UTC, hannes-ucsc commented
Thanks to @mikebaumann for his clever (and impressively clairvoyant) suggestion of using `must-not` and `range`.

2018-03-07 12:03 UTC, rexwangcc commented on scripts/v5_queries/smartseq2-query.json
> +            "files.biomaterial_json.biomaterials.content.biomaterial_core.ncbi_taxon_id": 9606
I think it is good for us to keep both the `must` and the `must not` for readability.

2018-03-07 12:03 UTC, rexwangcc commented on scripts/v5_queries/smartseq2-query.json
> +            "files.biomaterial_json.biomaterials.content.biomaterial_core.ncbi_taxon_id": 9606
Even they are functionally equal to each other.

2018-03-07 12:04 UTC, rexwangcc commented on scripts/v5_queries/smartseq2-query.json
> +            "field": "files.analysis_process_json"
Are there any further changes required for this field?

2018-03-07 12:09 UTC, rexwangcc approved these changes
LGTM. Special thanks to @mikebaumann who already provided the perfect solution to filter out human id 4 months ago!

2018-03-07 12:10 UTC, malloryfreeberg commented
I think the analysis must_not exists field needs to be:
"field": "files.process_json.analysis.analysis_process"

2018-03-07 12:52 UTC, samanehsan commented
Just fixed that field @malloryfreeberg! Thanks!

2018-03-07 19:22 UTC, malloryfreeberg commented
Great! There is now an example v5 bundle with an analysis process section here: https://github.com/HumanCellAtlas/metadata-schema/tree/malloryfreeberg-post_analysis_v5_bundle_example/examples/bundles/v5/Q4DemoSS2PostAnalysis

Once it's put in the data store, you can test the query out!

2018-03-07 19:23 UTC, malloryfreeberg approved these changes
Looks great!

2018-03-07 19:23 UTC, malloryfreeberg commented on scripts/v5_queries/smartseq2-query.json
> +      "must_not": [
I don't think this `must_not` will work. But, I need to add an analysis block to the current v5 process bundle so we can test this.

2018-03-07 19:23 UTC, malloryfreeberg commented on scripts/v5_queries/smartseq2-query.json
> +      "must_not": [
I think this must_not exists field needs to be 
`"field": "files.process_json.analysis.analysis_process"`

2018-03-07 23:49 UTC, hannes-ucsc requested changes

2018-03-07 23:49 UTC, hannes-ucsc commented on scripts/v5_queries/smartseq2-query.json
> +      "must_not": [
This does work:

```
          {
            "match": {
              "files.process_json.processes.content.process_type.text": "analysis"
            }
          },
```

2018-03-07 23:49 UTC, hannes-ucsc commented on scripts/v5_queries/smartseq2-query.json
> +            "files.process_json.biomaterial_collection.dissociation_process.dissociation_method": "FACS"
This doesn't look right. It's missing `.processes.content` after `process_json`

2018-03-07 23:49 UTC, hannes-ucsc commented on scripts/v5_queries/smartseq2-query.json
> +            "files.process_json.biomaterial_collection.dissociation_process.dissociation_method": "mouth pipette"
ditto

2018-03-08 10:33 UTC, malloryfreeberg commented on scripts/v5_queries/smartseq2-query.json
> +            "files.process_json.biomaterial_collection.dissociation_process.dissociation_method": "FACS"
Yes, I think this needs to be:
`files.process_json.processes.content.dissociation_method`

2018-03-12 15:17 UTC, samanehsan commented on scripts/v5_queries/smartseq2-query.json
> +            "files.process_json.biomaterial_collection.dissociation_process.dissociation_method": "FACS"
Can you explain why the field should be `enrichment_method` @malloryfreeberg? This was originally `files.assay_json.content.single_cell.cell_handling` in the v4 query and that maps to `files.process_json.processes.content.biomaterial_collection.dissociation_process.dissociation_method` according to the field mapping spreadsheet

2018-03-12 17:02 UTC, samanehsan commented
@hannes-ucsc I made the changes you requested! This query now matches the example v5 bundle in the data storage service (and not the one with the analysis process section)

2018-03-14 20:21 UTC, hannes-ucsc approved these changes

2018-03-14 21:16 UTC, merged